package com.example.alarmko.exceptions

enum class ErrorCode {
    ALARM_SCHEDULING_FAILED,
    ALARM_PERMISSION_DENIED,
    ALARM_INVALID_TITLE,
    ALARM_NO_MISSION_SELECTED,
    DATABASE_ERROR,
    DATABASE_INSERT_FAILED,
    DATABASE_UPDATE_FAILED,
    DATABASE_DELETE_FAILED,
    NOTIFICATION_ERROR,
    NOTIFICATION_PERMISSION_DENIED,
    MISSION_FAILED,
    MISSION_PHOTO_ERROR,
    MISSION_SENSOR_ERROR
}